language: emacs-lisp
env:
  - EVM_EMACS=emacs-24.5-travis
before_install:
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - git clone https://github.com/cask/cask.git /home/travis/.cask
  - export PATH="${HOME}/.evm/bin:${HOME}/.cask/bin:$PATH"
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
install:
  - cask install
script:
  - emacs --version
  - emacs -Q -batch -f batch-byte-compile *.el
